spring:
  application:
    name: spring-cloud-two-gateway
  profiles:
    active: dev
  # 开启 Gateway 服务注册中心服务发现
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: lb://SPRING-CLOUD-ONE-USER
          predicates:
            - Path=/v1/**
          filters:
            - RewritePath=/v1/(?<segment>.*), /$\{segment}

server:
  port: 10001

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      management.port: ${management.port}
  client:
    serviceUrl:
#      defaultZone: http://localhost:8000/eureka/
      defaultZone: http://devsvc.gltest.jpushoa.com/eureka

# 配置Gateway日志等级，输出转发细节信息
logging:
  level:
    org.springframework.cloud.gateway: debug
    com.netflix.discovery: debug
